<span class="title">Legal Terms of Use</span>
<p>
<strong>Use of Site</strong><br>
Access to and use of this site is subject to the terms and conditions set forth below ("Legal Terms"). Please carefully review the Legal Terms before accessing or using the site. Access and use of the site shall be deemed an acknowledgment of your rights and responsibilities with regard to the use and access of the site and agreement with the Legal Terms. 
<p></p>
Communities by Shea Homes are created through its independent members of the Shea family of companies (including, without limitation, Shea Homes, Inc. and Shea Homes Limited Partnership and any of their respective affiliates, partnerships or limited liability companies, all of which are collectively referred to as "Shea Homes"). Shea Homes may change the Legal Terms at any time by posting any such changes on the site. Any changes shall be effective upon posting. By accessing the site following the posting of any changes to the Legal Terms, you agree to all such changes. The contents, including images and text, within this site are copyrighted, and Shea Homes grants a limited license to viewers to download or print pages from the site for individual use only. Users may not otherwise use, copy, modify, distribute, republish or transmit any of the content or materials of the site without written permission of Shea Homes. 
<p></p>
<strong>Equal Housing Opportunity</strong><br>
It is the policy of Shea Homes to comply with both the letter and the spirit of the Federal Fair Housing Act, and amendments, which prohibit discrimination in the sale or rental of housing or vacant residential land based on race, color, religion, sex, handicap, familial status or national origin; and as to those Shea Homes' communities that are age restricted, to qualify for exemption from the familial status portion of the Fair Housing Act and all state age restrictions laws imposed by the state where a particular community is located. 
<p></p>
<strong>Void Where Prohibited By Law</strong><br>
This site and the related links do not constitute an offer to sell real property. Offers to sell real property may only be made and accepted at the sales center for the applicable community. The materials provided at this site are strictly for information purposes as a service to Internet users and shall not be construed as an offer in any jurisdiction where prior registration or other advance qualification of real property is required. Inquire at the applicable community to see if the real property is qualified for sale in your state. Responses will be limited if prior registration is required. Where required, no sale may occur until issuance of the final Subdivision Public Report required for the community.  Obtain the Subdivision Public Report or its equivalent, required by federal or state law, and read it before signing anything. No federal or state agency has judged the merit or value, if any, of this real property. Warning: the California Department of Real Estate has not inspected, examined or qualified communities outside California. 
<p></p>
Prospective buyers must visit the community to purchase a home or lot. Despite the efforts of Shea Homes to provide accurate information on this site, it is not possible to ensure that all information is correct or up to date. Any information also is subject to change. Shea Homes assumes no responsibility or liability for any actions taken as a result of using this site, or for errors or omissions in the content on this server. 
<p></p>
<strong>Intellectual Property</strong><br>
All copyrightable text, audio, video, graphics, charts, photographs and icons, design, selection, and arrangement of content in any medium on this site is copyrighted by Shea Homes, unless otherwise noted. The distinctive and original layout and presentation of this site also constitutes protectable trade dress under federal law. This site may also contain references to third-party marks, which are the property of their respective owners. Any unauthorized use of any of Shea Homes’ marks, or of its copyrighted material or trade dress or any other intellectual property, is strictly prohibited, and will be prosecuted to the fullest extent that the law provides. 
<p></p>
<strong>Liability Disclaimer</strong><br>
Despite the efforts of Shea Homes to provide accurate information, it is not possible to completely ensure that all information is constantly correct. Therefore, this site is provided by Shea Homes on an "AS IS" basis. Shea Homes disclaims all warranties with respect to this site, and to any information or products or services available on this site, including all implied warranties and conditions of merchantability, fitness for a particular purpose, title and non-infringement. Shea Homes also makes no warranty or representation regarding the results that may be obtained from this site, or regarding the accuracy or reliability of any information obtained from the site, or that its services will meet any user's requirements, be uninterrupted, timely, secure or error free. Shea Homes shall have no responsibility for the timeliness, deletion, mis-delivery or failure to store any user communications. 
<p></p>
No advice or information, whether oral or written, obtained by you from Shea Homes or through this site shall create any warranty. 
<p></p>
In no event shall Shea Homes or any of its subsidiaries, affiliates, officers, directors, employees, consultants or agents be liable for any direct, indirect, punitive, special, incidental, or consequential damages or any damages whatsoever, including, without limitation, damages for loss of use, data, information, profits or business interruption, arising out of or in any way related to the use or performance of this site or any linked site, to any information or products or anything else obtained through this site, or otherwise arising out of the use of this site, or to the inability to use the site, whether based in tort, contact, negligence, strict liability or otherwise, even if Shea Homes has been advised of the possibility of damages. Your sole and exclusive remedy is to discontinue using this site. 
<p></p>
Some states do not allow the exclusion or limitation of incidental or consequential damages, so some of the above limitations or exclusions may not apply to you. 
<p></p>
You understand and expressly agree that use of this site is at your own risk, that any material or data downloaded or otherwise obtained through the use of the site or by virtue of interaction with other users is at your own discretion and risk, and that you are solely responsible for any damage to your computer system or loss of data that results from the download of such material or data, and for any other form of damage that may be incurred. Shea Homes shall not be liable to users for any damage resulting from use of the site, nor is Shea Homes in any way responsible for the conduct of users, or information exchanged on the site. 
<p></p>
This site is intended to be for general reference purposes only. Shea Homes makes no guarantees with respect to any information provided on the site, and disclaims any warranties with respect to the accuracy of any mortgage calculators or other features of the site, or of any floor plans, square footage estimates, or other information on the site. The mortgage calculator and any other features are for informational purposes only, and are not an offer or a guarantee of a loan or an interest rate. Shea Homes makes no representation or guarantee regarding the investment status or future value of any home or lot. All renderings, elevations, and floor plans are an artist's conceptual drawings and may vary from actual plans and homes as built. Shea Homes reserves the right to change prices, floor plans, specifications, elevations, features, colors, prices and other terms without notice or obligation. 
<p></p>
<strong>Links to Other Sites</strong><br>
Shea Homes has not reviewed the Internet sites linked to this site, and is not responsible for the content of any off-site pages or any other sites linked to this site. Your linking to off-site pages or other sites is at your own risk. Shea Homes does not endorse any off-site pages, and is not responsible for any transmission or material received from any off-site pages. Shea Homes assumes no responsibility, and shall not be liable, for any viral infection of your computer equipment or software, or any other types of damages in any form, on account of your access, use of or browsing in this or any other site.